[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "c3408469f19da771fab822de04a74efc740e0b83"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "60de9c1347dec98f86e4e71146bbde3531f2e5701139d55e8aea71d2f458511c"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "eaa582f6a48db41c0abc61ae917552e5fd7e3e5f"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "4b4710c67076168bb0800d91e26bd523118f6b29da7fe925ddc578caabe541a2"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "c3408469f19da771fab822de04a74efc740e0b83"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "eede38eef2d34029a80d3d2706c74c8dfdeefa813f5f7d2b6bd505088f48b0e8"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3408469f19da771fab822de04a74efc740e0b83"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "f93b7dd312fb70504cc00d6dc0168f2ee2c9dd14cd6f1632db1dd387a78516a5"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-armv7l-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "c3408469f19da771fab822de04a74efc740e0b83"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "273636b860c9fa9ebeafdc175426e6a15b731e1bdfefbf70de67ae065bcb4aec"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "c3408469f19da771fab822de04a74efc740e0b83"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "14d9dc84bf7dbeaffd9efc7ef3c4e8854c03678cd53b1a5fd8bb6f58652a6b64"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "c3408469f19da771fab822de04a74efc740e0b83"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "4c5ab329c35c0db0ae931a23f4b81ff8230687962eb39295fd32ca3f71e4ca03"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "c3408469f19da771fab822de04a74efc740e0b83"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "89bb00b9748948edaee7a234d7491d6028bc1f06c54e0962aa17dd69c1216d1d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3408469f19da771fab822de04a74efc740e0b83"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "8b7c823beb938dca80d703aece00b8757f914423463a482967708f53eb7f52ac"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-armv7l-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "318e9d25d983aa68bfd8e0c2fb18fb389fbc86bb"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "82897385d8261d7b7af879e962bd05267ea57e3c77326ef75fa57fb957387727"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "318e9d25d983aa68bfd8e0c2fb18fb389fbc86bb"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "a24851272c5381332696a4ca56b13aef805baf1ef0b89049bffc6bbc922aab73"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-aarch64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "c3408469f19da771fab822de04a74efc740e0b83"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "6cd06236b542771ef3c8793763b290ccb7e36da45d1d599f7c2cd4282013dd04"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "ebdc57807c9ce1f307a6faefcbc2d7846e74e4ba"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "3ab94046259c6dead78c171f50ebdebe6e88b4f067954c5ab3e1afcd8c6d0bb5"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "ff46a953d718775790c5669fba1c11d7d9246a6e"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "acd0baff9851b875d318c62ce7dfce1eb373192ec82cf5c73e42ef9796667326"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.1.3/vegaliteassets-3.1.3-x86_64-w64-mingw32.tar.gz"
