[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "0d817f93d789ae79ee2bb247f1a56a70c2797103"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "7625de578ed9eaa1f11fc061cb3d5085afe577f24b931a87df5accd0eb0c52bf"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "82ed54ee8eefa2c7c5cdcec70907ab456fdff0a5"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "10efb7d3c0d25d7a05398e4fb7b88aab779a10c86421c7411acfaebb7a8cacc1"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "0d817f93d789ae79ee2bb247f1a56a70c2797103"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "92330a6e0fb6b2b5880f6af55f74475945032898d153fa02c4d0fd0c1dd1190f"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0d817f93d789ae79ee2bb247f1a56a70c2797103"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "e2bd4267bef2b305b6c1958ef60b64b57737f62f53ac4cc683e0044929ff3cab"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-armv7l-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "0d817f93d789ae79ee2bb247f1a56a70c2797103"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "d7697e2ca58429007bdecb9cc7823f6d38b93de22b92b0b9979e9e98fb517fa6"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "0d817f93d789ae79ee2bb247f1a56a70c2797103"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "38b42bdd8834d91a8e1a1e8b5f5d7db1cfb06043aaaf778316ed04212da63503"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "0d817f93d789ae79ee2bb247f1a56a70c2797103"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "dfd433de7d2634cab7d3514762b1a039ff78c30a3289fcb78b838b00d95704c4"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "0d817f93d789ae79ee2bb247f1a56a70c2797103"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "c025bce8b5dcda76c50fd6c36e077cfd0b29918144a2dd9937f748ff9c7c9e3e"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0d817f93d789ae79ee2bb247f1a56a70c2797103"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "ad811468b3893bd06f9bb633b888b4851fe64168708406687843987037f6f855"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-armv7l-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "7ee03a805e34399677f66bd92da1c51a835e24b5"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "7d0e5afa4cd07d1eb40f970b38bdd65bb71e1c0f5eade45bc9add91e1eaba304"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "7ee03a805e34399677f66bd92da1c51a835e24b5"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "db69cc2b7ca43fbf9749e3b9de0904f8721873d6e0f8be17d25c57e11a463e17"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-aarch64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "0d817f93d789ae79ee2bb247f1a56a70c2797103"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "7b50defd67a67a389c6db9bc0b18648d07eea71f05a72efa8bddd3b1b5280923"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "865410513864bdf256d38910b7a0d3e16e8ba859"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "b5e7197f1a8676a6f10b793ff2d71ff8d05ecfb52d567c97ba1fb275cf050c8a"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "06704f5fa3dc0763b1d9031e056bc07b83b4e627"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "c63005af8bd4f6eab6ce53ca3a29f8c8d6e77958c6b9f8dd1aa893435ea934b8"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.2.0/vegaliteassets-3.2.0-x86_64-w64-mingw32.tar.gz"
