[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "60e02ec2313cbf5cb27321d79ee9684894a5d985"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "676162937667640018c7e2da97594b0d5c717185a125aa06facd80888ef8dc8f"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "5e501c2671949a289ba0f086f23f09ec69035bbd"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "84984b71b4ce372af765b4559b8c88a8f7504eddc093517817ecbdd73f4c667c"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "60e02ec2313cbf5cb27321d79ee9684894a5d985"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "dbab1d12f3bee3fe36597df55c5e172435a7d33d0ebc23cc64ddaace0dec553d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "60e02ec2313cbf5cb27321d79ee9684894a5d985"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "bb7e32ea1bf3847b38af6376793350e6a5474fbf992bed633eb28edd1c4ed583"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-armv7l-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "60e02ec2313cbf5cb27321d79ee9684894a5d985"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "4769ccbbd9f89677276eb3cb3d9a4045c841d6e3663f06a82b68f6839fe574c8"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "60e02ec2313cbf5cb27321d79ee9684894a5d985"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "37088c9c8959733f9648c31e4b5f9ed69be1b5f79b670166ffd6fecba1f2ae65"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "60e02ec2313cbf5cb27321d79ee9684894a5d985"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "4abd871486ecebf053d16dc7e23a1f5b84baf764163914a023582d4415d410a7"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "60e02ec2313cbf5cb27321d79ee9684894a5d985"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "b053a6ba76a217449ead8aa2222fd80eee663ef5f737c0ecf0f0acbc7331fd1d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "60e02ec2313cbf5cb27321d79ee9684894a5d985"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "9db9771a770f3c60d000ab656cfd4f1491822b06a89c68858360d156eafed30a"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-armv7l-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "203c668d73758a923ae6d97087db83ab1938bea8"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "f6ca942d14398172b7037e3aa052b11e3d3effc36e5c11eba661bc149007864b"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "203c668d73758a923ae6d97087db83ab1938bea8"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "b2e4e0a29ff10cb41d8cd0dd20ddd37f739744f33d7d9c0040364b5d18642a51"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-aarch64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "60e02ec2313cbf5cb27321d79ee9684894a5d985"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "a9b191825d577baa3e7d6e05222500412482c469ff7771ab3c0c3e327d66dbb9"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "46d2dc4e09c94cd57713c48b539bca230be123b3"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "36140e405e9b221e8bb923b9e358950a50c95efeacd71d92ab4467cd5db67720"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "d7fca0b09d65277e70c511130fc455fb36247dd3"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "ac04ed70bd55fceb59a1494c8b587ea339c461c45397544651e21a3a5cbf78f0"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.3.0/vegaliteassets-3.3.0-x86_64-w64-mingw32.tar.gz"
